/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Peminjaman extends javax.swing.JFrame {
ModelPeminjaman rent = new ModelPeminjaman();
        
    
    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
        initComponents();
        setTitle("Pinjam Buku");
        
        load_tableBuku();
        load_tableMember();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableBuku = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableMember = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPinjam = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        fnama = new javax.swing.JTextField();
        fkode = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnBack = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Pengarang", "Penerbit"
            }
        ));
        TableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBuku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 410, 170));

        TableMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "TTL", "Alamat", "Pekerjaan"
            }
        ));
        TableMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMemberMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableMember);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 410, 140));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setText("Peminjaman Buku");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -10, 210, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Data Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Data Member");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 90, -1));

        btnPinjam.setText("Pinjam");
        btnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamActionPerformed(evt);
            }
        });
        getContentPane().add(btnPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 34, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 220, 40, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kode");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 40, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tgl Pinjam");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 300, 70, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tgl Kembali");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 340, 80, -1));
        getContentPane().add(fid, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 190, 30));
        getContentPane().add(fnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 190, 30));
        getContentPane().add(fkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 190, 30));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 190, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 90, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 190, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/image/Garis.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void load_tableBuku() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Kode Buku");
        dtm.addColumn("Judul");
        dtm.addColumn("Pengarang");
        dtm.addColumn("Penerbit");
        
        try {
            java.sql.Connection con; //METHOD MEMBUAT KONEKSI
            con = new KoneksiDatabase().connect();
            String sql = "SELECT * FROM `inputbuku`";
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery(sql);
            while (rs.next()){
                dtm.addRow(new Object[]{
                    rs.getString("kode"),
                    rs.getString("judul_buku"),
                    rs.getString("pengarang"),
                    rs.getString("penerbit"),
                    
                });
            }
            s.close();
            con.close();
           
            TableBuku.setModel(dtm);
        } catch (SQLException ex ) {
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "You got an Error!", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void load_tableMember() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       DefaultTableModel dtm2 = new DefaultTableModel();
        dtm2.addColumn("ID");
        dtm2.addColumn("Nama");
        dtm2.addColumn("TTL");
        dtm2.addColumn("Alamat");
        dtm2.addColumn("Pekerjaan");
        try {
            java.sql.Connection con2; //METHOD MEMBUAT KONEKSI
            con2 = new KoneksiDatabase().connect();
            String sql2 = "SELECT * FROM `inputmember`";
            Statement s2 = con2.createStatement();
            ResultSet rs2 = s2.executeQuery(sql2);
            while (rs2.next()){
                dtm2.addRow(new Object[]{
                    rs2.getString("id"),
                    rs2.getString("nama"),
                    rs2.getString("ttl"),
                    rs2.getString("alamat"),
                    rs2.getString("pekerjaan"),
                });
            }
            s2.close();
            con2.close();
           
            TableMember.setModel(dtm2);
        } catch (SQLException ex ) {
            Logger.getLogger(Peminjaman.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "You got an Error!", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }
      
    
    private void TableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBukuMouseClicked
        // TODO add your handling code here:
        int row = TableBuku.rowAtPoint(evt.getPoint());
        String kode = (String) TableBuku.getValueAt(row, 0);
                                                fkode.setText(kode);
    }//GEN-LAST:event_TableBukuMouseClicked

    private void TableMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMemberMouseClicked
        // TODO add your handling code here:
        int row = TableMember.rowAtPoint(evt.getPoint());
        fid.setText(TableMember.getValueAt(row, 0).toString());
        fnama.setText(TableMember.getValueAt(row, 1).toString());
        
    }//GEN-LAST:event_TableMemberMouseClicked

    private void btnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamActionPerformed
        // TODO add your handling code here:
        String id = fid.getText();
        String nama = fnama.getText();
        String kode = fkode.getText();
        String tgl_pinjam = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        String tgl_kembali = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        if (!fid.getText().isEmpty() && !fnama.getText().isEmpty() && !fkode.getText().isEmpty()
            && !tgl_pinjam.isEmpty()&& !tgl_kembali.isEmpty())
        {
            rent.pinjam(id,nama,kode,tgl_pinjam,tgl_kembali);
        }
    }//GEN-LAST:event_btnPinjamActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        int dialogbutton=JOptionPane.showOptionDialog(this, "Yakin ingin kembali", "Warning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (dialogbutton==JOptionPane.YES_OPTION){
            this.dispose();
            Menu m = new Menu();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBuku;
    private javax.swing.JTable TableMember;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPinjam;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fkode;
    private javax.swing.JTextField fnama;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

       
}
